### ISSUE TITLE
서버 구성하기

### ISSUE THREAD

**Issue by webispy** [webispy/travelhub#5]
서버: webispy.just4fun.co.kr
(기존에 쓰던 가상화서버 주말에 모두 초기화 시켰음)

가상화 서버이기 때문에, root 권한 있음.
필요시 계정 발급 가능.
현재 Ubuntu 12.10 설치되어 있음.
- 할일 -
  node.js + express로 기본 홈페이지 만들어서 동작 확인하기

**Comment by ghost** [comment]
http://165.213.96.171:3000/travel <--- 최종 확정 API URL?

**Comment by webispy** [comment]
no no~
연습한거에요. 서버도 사무실PC이고..
sample 이미지 구해서 정식 서버에 API 만들어 놓을게요
